// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs5uK17Gg7M-plgo8s3NU5K1vclsPtu8M',
    appId: '1:862356448705:web:e76516a34bb03887c53b40',
    messagingSenderId: '862356448705',
    projectId: 'badihi-329a6',
    authDomain: 'badihi-329a6.firebaseapp.com',
    storageBucket: 'badihi-329a6.firebasestorage.app',
    measurementId: 'G-YLS96QV0E6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJgmyk91QcsRym469E1vYrNRt6_kJmhSM',
    appId: '1:862356448705:android:932849b3e95ceb32c53b40',
    messagingSenderId: '862356448705',
    projectId: 'badihi-329a6',
    storageBucket: 'badihi-329a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAExjeCwUtI7a7o89hkXqSkxfMkF8SB2PM',
    appId: '1:862356448705:ios:647d8f6227e8a2afc53b40',
    messagingSenderId: '862356448705',
    projectId: 'badihi-329a6',
    storageBucket: 'badihi-329a6.firebasestorage.app',
    iosBundleId: 'com.badihi.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAExjeCwUtI7a7o89hkXqSkxfMkF8SB2PM',
    appId: '1:862356448705:ios:647d8f6227e8a2afc53b40',
    messagingSenderId: '862356448705',
    projectId: 'badihi-329a6',
    storageBucket: 'badihi-329a6.firebasestorage.app',
    iosBundleId: 'com.badihi.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCs5uK17Gg7M-plgo8s3NU5K1vclsPtu8M',
    appId: '1:862356448705:web:1ec0dbfbf9642d2bc53b40',
    messagingSenderId: '862356448705',
    projectId: 'badihi-329a6',
    authDomain: 'badihi-329a6.firebaseapp.com',
    storageBucket: 'badihi-329a6.firebasestorage.app',
    measurementId: 'G-L90V3LS670',
  );
}
